export const ANNOUNCEMENT_LIST_REQUEST = "ANNOUNCEMENT_LIST_REQUEST";
export const ANNOUNCEMENT_LIST_SUCCESS = "ANNOUNCEMENT_LIST_SUCCESS";
export const ANNOUNCEMENT_LIST_FAIL = "ANNOUNCEMENT_LIST_FAIL";

export const ANNOUNCEMENT_CREATE_REQUEST = "ANNOUNCEMENT_CREATE_REQUEST";
export const ANNOUNCEMENT_CREATE_SUCCESS = "ANNOUNCEMENT_CREATE_SUCCESS";
export const ANNOUNCEMENT_CREATE_FAIL = "ANNOUNCEMENT_CREATE_FAIL";
