export const ANNOUNCEMENT_LIST_REQUEST = "NOTE_LIST_REQUEST";
export const ANNOUNCEMENT_LIST_SUCCESS = "NOTE_LIST_SUCCESS";
export const ANNOUNCEMENT_LIST_FAIL = "NOTE_LIST_FAIL";

export const ANNOUNCEMENT_CREATE_REQUEST = "NOTE_CREATE_REQUEST";
export const ANNOUNCEMENT_CREATE_SUCCESS = "NOTE_CREATE_SUCCESS";
export const ANNOUNCEMENT_CREATE_FAIL = "NOTE_CREATE_FAIL";
